### ISSUE TITLE
Check for no extra properties

### ISSUE THREAD

**Issue by jamesharv** [mscharley/generic-type-guard#34]
It would be nice to be able to create a typeguard that is only true if the value being tested is an object that contains the exact set of properties specified, and no other extra properties.

**Comment by mscharley** [comment]
Proposal:

```
val isFoo = new tg.IsInterface().withProperty("foo", tg.isString).getExact();
```

This would be a `TypeGuard<{ foo: string }>` that would also check that there no extra properties defined.
