### ISSUE TITLE
global is not defined in browser

### ISSUE THREAD

**Issue by lukashass** [mscharley/generic-type-guard#452]
When using `generic-type-guard` in a browser environment, I receive the following error:

```
global is not defined
```

### Current workaround

I currently work around this issue by defining `window.global` somewhere before running `generic-type-guard` e.g. in a script tag.

```html
<script>window.global = window;</script>
```

### Proposed solution

`generic-type-guard` could add native support for browsers by using [globalThis](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) instead of `global`.

There is a tiny catch though: `globalThis` is [supported since Node 12](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis#browser_compatibility). So Node 10 could no longer be supported, which shouldn't be a problem since it is EOL anyway (https://nodejs.org/en/about/releases/).

**Comment by mscharley** [comment]
Hey Lukas,

Thanks for the compatibility report. I've no particular reason to support node 10 beyond that it just hasn't ever broken yet and this library is such a thin layer that I wanted to test support as far as I possibly could. Anyway, I was only referencing global as a disambiguation for naming things and there's other ways to fix that problem, so I solved it that way. Let me know if you still have issues with the new version!
