### ISSUE TITLE
isExactObject does not reject if object has additional properties

### ISSUE THREAD

**Issue by albanbruder** [mscharley/generic-type-guard#456]
See: https://github.com/mscharley/generic-type-guard/blob/main/src/objects.ts#L174

Do I understand this wrong?: "Validate that an object has exactly the fields provided" means that `isExactObject` should use `hasOnlyProperties` instead of `hasProperties`

Anyway: Great project! :rocket:

**Comment by mscharley** [comment]
Hmm, there isn't a test case that disambiguates that currently. That does seem reasonable based on the documentation and naming though. The tests were only half written in general, looks like I didn't entirely think this one through before committing it. Oops!

**Comment by mscharley** [comment]
This has been released as `generic-type-guard@3.6.0`.

**Comment by albanbruder** [comment]
Thanks a lot for fixing this!
