### ISSUE TITLE
Cannot use PartialTypeGuard in hasProperties/hasOnlyProperties

### ISSUE THREAD

**Issue by jakobo** [mscharley/generic-type-guard#466]
```ts
const isSample = tg.hasOnlyProperties({
  okay: tg.isBoolean,
  failing: tg.hasOnlyProperties({
    notokay: tg.isBoolean
  })
});
```

Error occurs on the `failing`, preventing combination of 

```
Type 'PartialTypeGuard<object, { notokay: boolean; }>' is not assignable to type 'TypeGuard<{ notokay: boolean; }>'.
  Types of parameters 'value' and 'value' are incompatible.
    Type 'unknown' is not assignable to type 'object'.ts(2322)
```

Is there an obvious way to combine nested types?

**Comment by mscharley** [comment]
What you're looking for is `tg.combine`.

```typescript
const isSample = tg.combine(
  tg.isObject,
  tg.hasOnlyProperties({
    okay: tg.isBoolean,
    failing: tg.combine(
      tg.isObject,
      tg.hasOnlyProperties({
        notokay: tg.isBoolean,
      }),
    ),
  }),
);
```

`PartialTypeGuard<A, B>` is a type that represents a guard that an input A is also a B. `TypeGuard<B>` is equivalent to `PartialTypeGuard<unknown, B>`. `tg.combine` lets you string together typeguards, so if you have `ab: PartialTypeGuard<A, B>` and `bc: PartialTypeGuard<B, C>` then `ac: PartialTypeGuard<A, C> = tg.combine(ab, bc)`.

There's also the `tg.IsInterface` builder that lets you build up object types like this with a bit nicer syntax, but off the top of my head I don't think it supports `hasOnlyProperties` at the moment.

**Comment by mscharley** [comment]
Since everything is a function, if you use this combination a lot you can create your own export in your application:

```
export const isObjectWithOnlyProperties = <T extends object>(props: tg.MappedTypeGuard<T>): tg.TypeGuard<T> =>
  tg.combine(tg.isObject, tg.hasOnlyProperties(props));
```
